# Generated by Django 4.2.13 on 2024-06-12 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('account_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Accounts', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('strSymbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Values', to='strategy.asset')),
            ],
        ),
        migrations.CreateModel(
            name='CoinexFutureAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_ID', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LyraAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionPrivateKey', models.CharField(max_length=255)),
                ('sessionPublicKey', models.CharField(max_length=255)),
                ('smart_Contract_Wallet_Address', models.CharField(max_length=255)),
                ('subAccountID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantBTCAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ParticipantBTCAddress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTCAddress', models.CharField(max_length=100)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Withdraws', to='strategy.assetvalue')),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategy.assetvalue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Withdraws', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txHash', models.CharField(max_length=255, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='strategy.participantbtcaddress')),
                ('assetValue', models.ManyToManyField(related_name='Transactions', to='strategy.assetvalue')),
                ('participants', models.ManyToManyField(related_name='Transactions', to='strategy.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastUSDCheck', models.IntegerField()),
                ('accounts', models.ManyToManyField(blank=True, to='strategy.account')),
                ('baseAssetValues', models.ManyToManyField(blank=True, related_name='Strategies', to='strategy.assetvalue')),
                ('currentAssetValues', models.ManyToManyField(blank=True, to='strategy.assetvalue')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategy.strategy'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btcROI', models.IntegerField()),
                ('usdROI', models.IntegerField()),
                ('ethROI', models.IntegerField()),
                ('date', models.DateField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Histories', to='strategy.strategy')),
            ],
        ),
    ]
