# Generated by Django 5.0.3 on 2024-05-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='strategy.account'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='baseAssetValues',
            field=models.ManyToManyField(blank=True, related_name='Strategies', to='strategy.assetvalue'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='currentAssetValues',
            field=models.ManyToManyField(blank=True, to='strategy.assetvalue'),
        ),
    ]
