# Generated by Django 5.0.3 on 2024-05-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_alter_strategy_accounts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinexfutureaccount',
            name='name',
        ),
    ]
