# Generated by Django 5.0.3 on 2024-05-27 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_remove_coinexfutureaccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btcROI', models.IntegerField()),
                ('usdROI', models.IntegerField()),
                ('ethROI', models.IntegerField()),
                ('date', models.DateField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Histories', to='strategy.strategy')),
            ],
        ),
    ]
