# Generated by Django 5.0.3 on 2024-05-28 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.FloatField()),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategy.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
