# Generated by Django 5.0.3 on 2024-05-29 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('paid', models.BooleanField(null=True)),
                ('btcAddress', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ParticipantBill', to='strategy.btcaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ParticipantBills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
