# Generated by Django 5.0.3 on 2024-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_btcaddress_participantbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='baseAssetValues',
            field=models.ManyToManyField(blank=True, null=True, related_name='Participants', to='strategy.assetvalue'),
        ),
        migrations.AddField(
            model_name='participant',
            name='created',
            field=models.DateField(null=True),
        ),
    ]
