# Generated by Django 5.0.3 on 2024-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_participant_baseassetvalues_participant_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='lastUSDCheck',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='baseAssetValues',
            field=models.ManyToManyField(blank=True, related_name='Participants', to='strategy.assetvalue'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateField(auto_now_add=True, default='2024-05-29'),
            preserve_default=False,
        ),
    ]
