# Generated by Django 5.0.3 on 2024-05-29 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0008_strategy_lastusdcheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='lastUSDCheck',
            field=models.IntegerField(),
        ),
    ]
