# Generated by Django 5.0.3 on 2024-05-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0009_alter_strategy_lastusdcheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantbill',
            old_name='paid',
            new_name='accepted',
        ),
        migrations.AddField(
            model_name='participantbill',
            name='userIsDone',
            field=models.BooleanField(default=False),
        ),
    ]
