# Generated by Django 5.0.3 on 2024-05-30 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_rename_paid_participantbill_accepted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantBTCAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btcAddress', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ParticipantBTCAddress', to='strategy.btcaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ParticipantBTCAddresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txi', models.CharField(max_length=255, unique=True)),
                ('converted', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='strategy.btcaddress')),
            ],
        ),
        migrations.DeleteModel(
            name='ParticipantBill',
        ),
    ]
