# Generated by Django 5.0.3 on 2024-05-30 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0011_participantbtcaddress_payment_delete_participantbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='txi',
            new_name='txHash',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Payments', to='strategy.participantbtcaddress'),
        ),
    ]
