# Generated by Django 5.0.3 on 2024-05-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0012_rename_txi_payment_txhash_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='converted',
        ),
        migrations.AddField(
            model_name='payment',
            name='participants',
            field=models.ManyToManyField(related_name='Payments', to='strategy.participant'),
        ),
    ]
