# Generated by Django 5.0.3 on 2024-05-31 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0013_remove_payment_converted_payment_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='assetValue',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='Payments', to='strategy.assetvalue'),
            preserve_default=False,
        ),
    ]
