# Generated by Django 5.0.3 on 2024-05-31 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0014_remove_payment_amount_payment_assetvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txHash', models.CharField(max_length=255, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='strategy.participantbtcaddress')),
                ('assetValue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transactions', to='strategy.assetvalue')),
                ('participants', models.ManyToManyField(related_name='Transactions', to='strategy.participant')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
