# Generated by Django 5.0.3 on 2024-05-31 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0016_remove_participantbtcaddress_btcaddress_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantbtcaddress',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ParticipantBTCAddress', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
