# Generated by Django 5.0.3 on 2024-06-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0019_transaction_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyraAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionPrivateKey', models.CharField(max_length=255)),
                ('smart_Contract_Wallet_Address', models.CharField(max_length=255)),
                ('subAccountID', models.IntegerField()),
            ],
        ),
    ]
