# Generated by Django 5.0.3 on 2024-06-08 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0020_lyraaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BTCAddress', models.CharField(max_length=100)),
                ('consideration', models.TextField()),
                ('status', models.BooleanField(blank=True, null=True)),
                ('amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Withdraws', to='strategy.assetvalue')),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='strategy.assetvalue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Withdraws', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
