# Generated by Django 5.0.3 on 2024-06-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0021_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='consideration',
        ),
    ]
