# Generated by Django 5.0.3 on 2024-06-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0022_remove_withdraw_consideration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyraaccount',
            name='sessionPublicKey',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
