# Generated by Django 5.0.3 on 2024-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0023_lyraaccount_sessionpublickey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyraaccount',
            name='sessionPublicKey',
            field=models.CharField(max_length=255),
        ),
    ]
