# Generated by Django 4.2.13 on 2024-06-12 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('apiIdentifier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exactCreationtResponse', models.TextField(unique=True)),
                ('orderID', models.CharField(max_length=50)),
                ('executed', models.BooleanField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Orders', to='gridbot.contract')),
            ],
        ),
        migrations.CreateModel(
            name='GridBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('interval', models.IntegerField(default=60)),
                ('lastTimeCheck', models.DateTimeField(blank=True, null=True)),
                ('position', models.FloatField(default=0)),
                ('account_id', models.IntegerField()),
                ('account_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GridBots', to='contenttypes.contenttype')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GridBots', to='gridbot.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='GridBots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.FloatField()),
                ('buy', models.FloatField()),
                ('size', models.FloatField()),
                ('nextPosition', models.IntegerField(choices=[(1, 'sell'), (2, 'buy')])),
                ('status', models.IntegerField(choices=[(0, 'start'), (1, 'open'), (2, 'filled'), (3, 'pause')])),
                ('is_active', models.BooleanField(default=True)),
                ('gridbot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Grids', to='gridbot.gridbot')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grid', to='gridbot.order')),
                ('orders', models.ManyToManyField(blank=True, related_name='Grids', to='gridbot.order')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_model', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contracts', to='gridbot.exchange'),
        ),
        migrations.CreateModel(
            name='CoinexAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('access_ID', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CoinexAccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AevoAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('API_Key', models.CharField(max_length=200)),
                ('API_Secret', models.CharField(max_length=200)),
                ('Signing_Key', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AevoAccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
