# Generated by Django 5.0.3 on 2024-05-01 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridbot',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='gridbot',
            name='contract_model',
        ),
        migrations.AddField(
            model_name='gridbot',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='GridBots', to='gridbot.contract'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Orders', to='gridbot.contract'),
        ),
        migrations.AlterField(
            model_name='grid',
            name='orders',
            field=models.ManyToManyField(blank=True, to='gridbot.order'),
        ),
    ]
