# Generated by Django 4.2.13 on 2024-06-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aevoaccount',
            old_name='exchangeID',
            new_name='account_id',
        ),
    ]
