# Generated by Django 4.2.13 on 2024-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0002_alter_order_exactcreationtresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='priceDeciminal',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='contract',
            name='sizeDeciminal',
            field=models.IntegerField(default=2),
        ),
    ]
