# Generated by Django 4.2.13 on 2024-06-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0002_rename_exchangeid_aevoaccount_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinexaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
