# Generated by Django 5.0.3 on 2024-05-11 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gridbot', '0002_gridbot_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contracts', to='gridbot.exchange'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='account_model',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='requiredMargin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Contracts', to='gridbot.asset'),
        ),
    ]
