# Generated by Django 4.2.13 on 2024-06-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0003_contract_pricedeciminal_contract_sizedeciminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aevoaccount',
            name='API_Key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aevoaccount',
            name='API_Secret',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aevoaccount',
            name='Signing_Key',
            field=models.CharField(max_length=255),
        ),
    ]
