# Generated by Django 5.0.3 on 2024-05-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0003_asset_alter_contract_exchange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='requiredMargin',
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
