# Generated by Django 4.2.13 on 2024-06-12 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gridbot', '0003_coinexaccount_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aevo_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('account_id', models.CharField(blank=True, max_length=200, null=True)),
                ('API_Key', models.CharField(max_length=200)),
                ('API_Secret', models.CharField(max_length=200)),
                ('Signing_Key', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AevoAccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AevoAccount',
        ),
    ]
