# Generated by Django 5.0.3 on 2024-05-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0004_remove_contract_requiredmargin_delete_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinexaccount',
            name='access_ID',
        ),
        migrations.RemoveField(
            model_name='coinexaccount',
            name='secret_key',
        ),
        migrations.AddField(
            model_name='coinexaccount',
            name='access_ID_encrypted',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinexaccount',
            name='secret_key_encrypted',
            field=models.CharField(default='asdsad', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coinexaccount',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
