# Generated by Django 5.0.3 on 2024-05-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0005_remove_coinexaccount_access_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinexaccount',
            name='access_ID_encrypted',
        ),
        migrations.RemoveField(
            model_name='coinexaccount',
            name='secret_key_encrypted',
        ),
        migrations.AddField(
            model_name='coinexaccount',
            name='access_ID',
            field=models.CharField(default='asdsad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinexaccount',
            name='secret_key',
            field=models.CharField(default='Asdasd', max_length=100),
            preserve_default=False,
        ),
    ]
