# Generated by Django 5.0.3 on 2024-05-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0006_remove_coinexaccount_access_id_encrypted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinexaccount',
            name='access_ID',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coinexaccount',
            name='secret_key',
            field=models.CharField(max_length=200),
        ),
    ]
