# Generated by Django 5.0.3 on 2024-05-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0007_alter_coinexaccount_access_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grid',
            old_name='bot',
            new_name='gridbot',
        ),
        migrations.RemoveField(
            model_name='gridbot',
            name='lastTrueCheck',
        ),
    ]
