# Generated by Django 5.0.3 on 2024-05-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0011_alter_grid_order_alter_grid_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grid', to='gridbot.order'),
        ),
    ]
