# Generated by Django 5.0.3 on 2024-05-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0012_alter_grid_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='lastTimeCheck',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
