# Generated by Django 5.0.3 on 2024-06-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0013_gridbot_lasttimecheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridbot',
            name='position',
            field=models.FloatField(default=0),
        ),
    ]
