# Generated by Django 5.0.3 on 2024-06-09 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0014_gridbot_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LyraAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sessionPublicKey', models.CharField(max_length=255)),
                ('sessionPrivateKey', models.CharField(max_length=255)),
                ('smart_Contract_Wallet_Address', models.CharField(max_length=255)),
                ('subAccountID', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LyraAccountAccounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
