# Generated by Django 4.2.13 on 2024-06-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0017_aevoaccount_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aevoaccount',
            old_name='address',
            new_name='ExchangeID',
        ),
    ]
