# Generated by Django 4.2.13 on 2024-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0018_rename_address_aevoaccount_exchangeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinexaccount',
            name='ExchangeID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aevoaccount',
            name='ExchangeID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
