# Generated by Django 4.2.13 on 2024-06-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0019_coinexaccount_exchangeid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aevoaccount',
            old_name='ExchangeID',
            new_name='exchangeID',
        ),
        migrations.RenameField(
            model_name='coinexaccount',
            old_name='ExchangeID',
            new_name='exchangeID',
        ),
    ]
