# Generated by Django 4.2.13 on 2024-06-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gridbot', '0020_rename_exchangeid_aevoaccount_exchangeid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinexaccount',
            name='exchangeID',
        ),
    ]
