# Generated by Django 4.2.13 on 2026-06-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegramChatID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
