# Generated by Django 5.0.3 on 2024-04-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_vipexpiration_delete_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='TOTPKey',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
