# Generated by Django 5.0.3 on 2024-06-03 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_totpkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPBTCAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VIPBTCAddresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
